        
        <footer id="footer">
          	
			<div id="newsletter">
				<form>
					<input type="text" placeholder="email" />
					<input type="submit" text="submit" />
				</form>
			</div>
			
			<div id="signature">
				<span class="icon-signature"> </span>
			</div>	
			<div id="social-links">
				<a href="http://facebook.com/suffoca" target=_blank> 
					<span class="">Facebook </span>   
				</a>
				<a href="http://twitter.com/suffoca" target=_blank> 
					<span class="">Twitter </span>    
				</a>
				<a href="http://youtube.com/suffoca" target=_blank> 
					<span class="">Youtube </span>    
				</a>
				<a href="http://instagram.com/suffoca" target=_blank> 
					<span class="">Instagram </span>  
				</a>
			</div>
            <p id="copyright"> 
				All content &copy; SUFFOCA™ 2008-2015 
			</p>	
        </footer>
		
		
		<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.1.min.js"><\/script>')</script>
        <script src="js/plugins.js"></script>
        <script src="js/vendor/slick.js"></script>
		
		
		<script src="js/gsap/TweenMax.min.js"> </script>
		<!-- // <script src="js/gsap/ScrollToPlugin.min.js"> </script> -->
		<!-- // <script src="js/gsap/TextPlugin.min.js"> </script> -->
		<script src="js/jquery.scrollmagic.min.js"></script>
		
		<script src="js/jquery.scrollmagic.debug.js"></script>
		
		<script src="js/anim.js"></script>
		
		
		
        <script src="js/main.js"></script>

        <script>
            var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']];
            (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
            g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
            s.parentNode.insertBefore(g,s)}(document,'script'));
        </script>
    </body>
</html>
