		<link rel="stylesheet" href="css/base.css">  <!-- Reset & Browser Independent -->
        <link rel="stylesheet" href="css/main.css"> <!-- Advanced & Browser Dependent -->

   </head>
        <body>

        <header id="header">
        	<a id="toggle" href="#primary"> <span class="icon-face"></span> </a>
        	<a id="logotype" href="/"> <h1> <span class="icon-suffoca"></span> </h1> </a>
        	<div id="cart">
        		<a href="/shop"> Shop </a>
        		<a href="/cart"> <span class="icon-cart"></span> </a>
        	</div>
        </header>

        <nav id="primary">
			<ul>
				<li> <a href="/story"> Our Story </a> </li>
				<li> <a href="/characters"> The Characters </a> </li>
				<li> <a href="/shop"> Shop </a> </li>
				<li> <a href="/contact"> Get In Touch </a> </li>
			</ul>
    	</nav>